name: CI
on: [push, pull_request]
env: 
  EV_secret: ${{ secret.TESTING_SECRET }}
jobs:
    build:
        name: Run Script
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: Script
            run: .\.github\scripts\script.ps1
            shell: pwsh