name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
        - name: echo a string
          run: echo "Hello Github Action World"
        - name: multipleline script
          run: |
            node -v
            npm -v